# Generated by Django 2.2.3 on 2020-04-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='weak_from', to='pokemon_entities.PokemonElementType', verbose_name='Силён против'),
        ),
    ]
